Iter13
NevostruevK/metric pull request #14
Opened 2023-04-17 11:50 UTC by NevostruevK

2023-04-18 21:50 UTC, tmvrus requested changes
в тестах для логирования используется fmt.Println, хотя у testing.T есть удобный метод Log, рекомендую начать использовать его.

2023-04-18 21:50 UTC, tmvrus commented on internal/db/postgres.go
> +func (db *DB) ShowMetrics(ctx context.Context) error {
эта ф-я выглядит почти так же как GetAllMetrics, возможно стоит использовать GetAllMetrics что бы получить список метрик, а в этой просто их "напечатать"

2023-04-18 21:50 UTC, tmvrus commented on internal/db/postgres.go
> +	db.logger.Println("Show metrics")
зачем понадобилось создавать новый логер если уже есть db.logger?

2023-04-18 21:50 UTC, tmvrus commented on internal/db/postgres.go
> +	sM := make([]metrics.Metrics, 0, size+10)
почему тут 10 а не 20 или 30?
классическая "магическая константа", смысл ее доступен только автору кода - рекомендую использовать вместо цифр константы с говорящими названиями

2023-04-18 21:50 UTC, tmvrus commented on internal/db/postgres.go
> +}
тут допущена ошибка: транзакция существует  сама по себе, db.AddMetric - сам по себе. для того что бы запросы выполнялись внутри транзакции - нужно использовать методы структуры tx (то что возвращает BeginTx)

2023-04-18 21:50 UTC, tmvrus commented on internal/db/postgres.go
> +func (db *DB) AddMetric(ctx context.Context, rt storage.RepositoryData) error {
тут точно такая же ошибка - транзакция существует сама по себе.
Еще хочу отметить, что создавать транзакцию для одного запроса нет смысла.

2023-04-18 21:50 UTC, tmvrus commented on cmd/server/main.go
> +		fmt.Println("Can't compleate DB connection: ", err)
в рамках этого спринта нужно перестать использовать пакет fmt для логирования

2023-04-18 21:50 UTC, tmvrus commented on internal/util/logger/logger.go
> +}
загадочные ф-и с разными именами но одинаковой сутью

2023-04-18 21:50 UTC, tmvrus commented on internal/server/server.go
> +	logger.Fatal(server.ListenAndServe())
если сервис сможет стартовать, logger.Fatal уже никогда не выполнится, поскольку нигде не вызывается завершение работы сервера - http.Server{}.Shutdown
а это важное условие graceful shutdown,

общий алгоритм должен быть следующий
- получение сигнала от ОС
- http.Server{}.Shutdown
- db.Close()
- выход из приложения

2023-04-19 07:53 UTC, NevostruevK commented on internal/db/postgres.go
> +func (db *DB) ShowMetrics(ctx context.Context) error {
исправил

2023-04-19 07:54 UTC, NevostruevK commented on internal/db/postgres.go
> +	db.logger.Println("Show metrics")
Исправил
Хотел, чтобы при печати метрик не выводилась лишняя информация (без флагов log.LstdFlags|log.Lshortfile )

2023-04-19 08:04 UTC, NevostruevK commented on internal/db/postgres.go
> +	sM := make([]metrics.Metrics, 0, size+10)
Увеличил размер, вдруг кто-то прямо во время выполнения запроса успеет десять метрик записать )
const extraSizeIfNewMetricsWereJustSaved = 10

2023-04-19 09:52 UTC, NevostruevK commented on internal/db/postgres.go
> +}
переделал вызовы с tx. .., к сожалению не смог не продублировать код функции с транзакцией и без.
Еще добавил в Handler /updates/ подготовку слайса перед записью в БД (обработал дублирующиеся метрики)

2023-04-19 10:59 UTC, NevostruevK commented on internal/db/postgres.go
> +func (db *DB) AddMetric(ctx context.Context, rt storage.RepositoryData) error {
убрал транзакцию

2023-04-19 11:00 UTC, NevostruevK commented on cmd/server/main.go
> +		fmt.Println("Can't compleate DB connection: ", err)
Поправил

2023-04-19 11:20 UTC, NevostruevK commented on internal/util/logger/logger.go
> +}
одну загадочную NewServer убрал

2023-04-19 13:45 UTC, NevostruevK commented on internal/server/server.go
> +	logger.Fatal(server.ListenAndServe())
Исправил

2023-04-19 19:56 UTC, tmvrus approved these changes

2023-08-08 06:04 UTC, merged