Iter24
NevostruevK/metric pull request #24
Opened 2023-08-04 13:54 UTC by NevostruevK

2023-08-07 21:44 UTC, tmvrus requested changes
- все что не касатеся 10 спринта нужно смержить в main
- в PR должны остаться только инкременты 23 и 24

2023-08-07 21:44 UTC, tmvrus commented on cmd/agent/main.go
> +	fmt.Println(cfg)
использование fmt для логирование не рекомендовано, это материал 3го спринта

2023-08-07 21:44 UTC, tmvrus commented on cmd/server/main.bkp
> +package main
это что за мусор?

2023-08-08 05:57 UTC, NevostruevK commented on cmd/agent/main.go
> +	fmt.Println(cfg)
исправил

2023-08-08 06:00 UTC, NevostruevK commented on cmd/server/main.bkp
> +package main
Убрал.
В папке grpc/server оставил bkp файлы юнит тестов. Почему-то на гитхабе они не проходят, локально работают.

2023-08-08 06:03 UTC, NevostruevK commented on cmd/agent/main.go
> +	fmt.Println(cfg)
22-ой инкремент смержил в main

2023-08-08 09:08 UTC, closed without merging